/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import db.DatabaseManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ZINAB
 */
public class ManageMedicalRecordUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMedicalRecordUI.class.getName());

    /**
     * Creates new form ManageMedicalRecordUI
     */
    public ManageMedicalRecordUI() {
        initComponents();
        setupManageMedicalRecordUI();
    }

    // Wire UI events and load the available patients when the screen opens.
    private void setupManageMedicalRecordUI() {
        setTitle("Manage Medical Record");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        SaveChangesButton.addActionListener(e -> saveMedicalRecord());
        SelectRecordComboBox.addActionListener(e -> loadSelectedMedicalRecord());
        loadPatientsIntoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavPanel = new javax.swing.JPanel();
        NavLabel = new javax.swing.JLabel();
        PatientMonitoringLabel = new javax.swing.JLabel();
        SelectRecordComboBox = new javax.swing.JComboBox<>();
        CommentPanel = new javax.swing.JPanel();
        CommentLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SelectRecordLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TreatmentPlanLabel = new javax.swing.JLabel();
        AllergiesLabel = new javax.swing.JLabel();
        DiagnosisLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        AllergiesTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        TreatmentPlanTextArea = new javax.swing.JTextArea();
        MedicationLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        DoctorNotesTextArea = new javax.swing.JTextArea();
        ClinicalDetailsLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        HbAlcPanel = new javax.swing.JPanel();
        HbAlcTypeLabel = new javax.swing.JLabel();
        HbAlcNumberLabel = new javax.swing.JLabel();
        HbAlcLabel = new javax.swing.JLabel();
        ViewLaboratoryResultsLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        FooterPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        SaveChangesButton = new javax.swing.JButton();
        DoctorNotesLabel = new javax.swing.JLabel();
        FastingGlucosePanel = new javax.swing.JPanel();
        FastingGlucoseTypeLabel = new javax.swing.JLabel();
        FastingGlucoseNumberLabel = new javax.swing.JLabel();
        FastingGlucoseLabel = new javax.swing.JLabel();
        CreatininePanel = new javax.swing.JPanel();
        CreatinineTypeLabel = new javax.swing.JLabel();
        CreatinineNumberLabel = new javax.swing.JLabel();
        CreatinineLabel = new javax.swing.JLabel();
        LDLcholesterolPanel = new javax.swing.JPanel();
        LDLcholesterolTypeLabel = new javax.swing.JLabel();
        LDLcholesterolNumberLabel = new javax.swing.JLabel();
        LDLcholesterolLabel = new javax.swing.JLabel();
        HeartratePanel = new javax.swing.JPanel();
        HeartrateLabel = new javax.swing.JLabel();
        HeartrateNumberLabel = new javax.swing.JLabel();
        BloodPressurPanel = new javax.swing.JPanel();
        BloodpressureLabel = new javax.swing.JLabel();
        BloodpressureNumberLabel = new javax.swing.JLabel();
        SpO2Panel = new javax.swing.JPanel();
        SpO2Label = new javax.swing.JLabel();
        SpO2NumberLabel = new javax.swing.JLabel();
        TemperaturePanel = new javax.swing.JPanel();
        TemperatureLabel = new javax.swing.JLabel();
        TemperatureNumberLabel = new javax.swing.JLabel();
        HbAlcPanel1 = new javax.swing.JPanel();
        HbAlcLabel1 = new javax.swing.JLabel();
        HbAlcNumberLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        DiagnosisTextArea = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        MedicationTextArea = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        RespiratoryRatePanel = new javax.swing.JPanel();
        RespiratoryRateLabel = new javax.swing.JLabel();
        RespiratoryRateNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().setPreferredSize(new java.awt.Dimension(870, 640));
        getContentPane().setLayout(null);

        NavPanel.setBackground(new java.awt.Color(91, 139, 217));
        NavPanel.setForeground(new java.awt.Color(255, 255, 255));

        NavLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NavLabel.setForeground(new java.awt.Color(255, 255, 255));
        NavLabel.setText("Manage Medical Record");

        javax.swing.GroupLayout NavPanelLayout = new javax.swing.GroupLayout(NavPanel);
        NavPanel.setLayout(NavPanelLayout);
        NavPanelLayout.setHorizontalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(NavLabel)
                .addContainerGap(623, Short.MAX_VALUE))
        );
        NavPanelLayout.setVerticalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NavLabel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        addAbsolute(NavPanel, 0, 0, 870, 70);

        PatientMonitoringLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PatientMonitoringLabel.setForeground(new java.awt.Color(91, 139, 217));
        PatientMonitoringLabel.setText("PATIENT MONITORING");
        addAbsolute(PatientMonitoringLabel, 560, 350, -1, 20);

        SelectRecordComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addAbsolute(SelectRecordComboBox, 120, 80, 370, 30);

        CommentPanel.setBackground(new java.awt.Color(230, 240, 250));
        CommentPanel.setForeground(new java.awt.Color(255, 255, 255));

        CommentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CommentLabel.setForeground(new java.awt.Color(0, 0, 0));
        CommentLabel.setText(" Lab results and monitoring data have been retrieved.");

        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("●");

        javax.swing.GroupLayout CommentPanelLayout = new javax.swing.GroupLayout(CommentPanel);
        CommentPanel.setLayout(CommentPanelLayout);
        CommentPanelLayout.setHorizontalGroup(
            CommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentLabel)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        CommentPanelLayout.setVerticalGroup(
            CommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommentLabel)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        addAbsolute(CommentPanel, 30, 140, 460, 40);

        SelectRecordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SelectRecordLabel.setForeground(new java.awt.Color(91, 139, 217));
        SelectRecordLabel.setText("Select record:");
        addAbsolute(SelectRecordLabel, 20, 80, -1, 20);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(91, 139, 217));
        addAbsolute(jSeparator1, 560, 370, 280, 10);

        TreatmentPlanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TreatmentPlanLabel.setForeground(new java.awt.Color(25, 41, 105));
        TreatmentPlanLabel.setText("Treatment plan");
        addAbsolute(TreatmentPlanLabel, 270, 250, -1, -1);

        AllergiesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AllergiesLabel.setForeground(new java.awt.Color(25, 41, 105));
        AllergiesLabel.setText("Allergies");
        addAbsolute(AllergiesLabel, 270, 350, -1, -1);

        DiagnosisLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiagnosisLabel.setForeground(new java.awt.Color(25, 41, 105));
        DiagnosisLabel.setText("Diagnosis");
        addAbsolute(DiagnosisLabel, 30, 250, -1, -1);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 41, 105));
        jLabel9.setText("Diagnosis");

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBar(null);

        AllergiesTextArea.setColumns(20);
        AllergiesTextArea.setRows(5);
        jScrollPane4.setViewportView(AllergiesTextArea);

        jScrollPane3.setViewportView(jScrollPane4);

        addAbsolute(jScrollPane3, 270, 380, 210, 50);

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setHorizontalScrollBar(null);

        TreatmentPlanTextArea.setColumns(20);
        TreatmentPlanTextArea.setRows(5);
        jScrollPane6.setViewportView(TreatmentPlanTextArea);

        jScrollPane5.setViewportView(jScrollPane6);

        addAbsolute(jScrollPane5, 270, 280, 210, 50);

        MedicationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MedicationLabel.setForeground(new java.awt.Color(25, 41, 105));
        MedicationLabel.setText("Medications");
        addAbsolute(MedicationLabel, 30, 350, -1, -1);

        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setHorizontalScrollBar(null);

        DoctorNotesTextArea.setColumns(20);
        DoctorNotesTextArea.setRows(5);
        jScrollPane7.setViewportView(DoctorNotesTextArea);

        addAbsolute(jScrollPane7, 30, 480, 420, 40);

        ClinicalDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClinicalDetailsLabel.setForeground(new java.awt.Color(91, 139, 217));
        ClinicalDetailsLabel.setText("CLINICAL DETAILS");
        addAbsolute(ClinicalDetailsLabel, 20, 200, -1, 20);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(91, 139, 217));
        addAbsolute(jSeparator2, 20, 230, 490, 10);

        HbAlcPanel.setBackground(new java.awt.Color(238, 243, 249));

        HbAlcTypeLabel.setForeground(new java.awt.Color(255, 152, 0));
        HbAlcTypeLabel.setText("Elevated");

        HbAlcNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HbAlcNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        HbAlcNumberLabel.setText("7.2 %");

        HbAlcLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HbAlcLabel.setForeground(new java.awt.Color(25, 41, 105));
        HbAlcLabel.setText("HbAlc");

        javax.swing.GroupLayout HbAlcPanelLayout = new javax.swing.GroupLayout(HbAlcPanel);
        HbAlcPanel.setLayout(HbAlcPanelLayout);
        HbAlcPanelLayout.setHorizontalGroup(
            HbAlcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HbAlcPanelLayout.createSequentialGroup()
                .addGroup(HbAlcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HbAlcPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HbAlcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HbAlcNumberLabel)
                            .addComponent(HbAlcTypeLabel)))
                    .addGroup(HbAlcPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(HbAlcLabel)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        HbAlcPanelLayout.setVerticalGroup(
            HbAlcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HbAlcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HbAlcLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HbAlcNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HbAlcTypeLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        addAbsolute(HbAlcPanel, 570, 140, 100, 80);

        ViewLaboratoryResultsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewLaboratoryResultsLabel.setForeground(new java.awt.Color(91, 139, 217));
        ViewLaboratoryResultsLabel.setText("VIEW LABORATORY RESULTS");
        addAbsolute(ViewLaboratoryResultsLabel, 560, 90, -1, 20);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(91, 139, 217));
        addAbsolute(jSeparator3, 560, 120, 290, 10);

        FooterPanel.setBackground(new java.awt.Color(183, 204, 228));
        FooterPanel.setForeground(new java.awt.Color(183, 204, 228));

        CancelButton.setBackground(new java.awt.Color(255, 255, 255));
        CancelButton.setForeground(new java.awt.Color(0, 51, 153));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(this::CancelButtonActionPerformed);

        SaveChangesButton.setBackground(new java.awt.Color(91, 139, 217));
        SaveChangesButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveChangesButton.setText("Save changes");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(633, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(32, 32, 32)
                .addComponent(SaveChangesButton)
                .addGap(32, 32, 32))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        addAbsolute(FooterPanel, 0, 570, 870, 70);

        DoctorNotesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DoctorNotesLabel.setForeground(new java.awt.Color(25, 41, 105));
        DoctorNotesLabel.setText("Doctor notes");
        addAbsolute(DoctorNotesLabel, 30, 450, -1, -1);

        FastingGlucosePanel.setBackground(new java.awt.Color(238, 243, 249));

        FastingGlucoseTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        FastingGlucoseTypeLabel.setForeground(new java.awt.Color(255, 152, 0));
        FastingGlucoseTypeLabel.setText("Abovr range");

        FastingGlucoseNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FastingGlucoseNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        FastingGlucoseNumberLabel.setText("128 mg/dl");

        FastingGlucoseLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FastingGlucoseLabel.setForeground(new java.awt.Color(25, 41, 105));
        FastingGlucoseLabel.setText("Fasting glucose");

        javax.swing.GroupLayout FastingGlucosePanelLayout = new javax.swing.GroupLayout(FastingGlucosePanel);
        FastingGlucosePanel.setLayout(FastingGlucosePanelLayout);
        FastingGlucosePanelLayout.setHorizontalGroup(
            FastingGlucosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FastingGlucosePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FastingGlucosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FastingGlucoseNumberLabel)
                    .addComponent(FastingGlucoseTypeLabel)
                    .addComponent(FastingGlucoseLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        FastingGlucosePanelLayout.setVerticalGroup(
            FastingGlucosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FastingGlucosePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FastingGlucoseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FastingGlucoseNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FastingGlucoseTypeLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        addAbsolute(FastingGlucosePanel, 720, 140, 110, 80);

        CreatininePanel.setBackground(new java.awt.Color(238, 243, 249));

        CreatinineTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        CreatinineTypeLabel.setForeground(new java.awt.Color(76, 175, 80));
        CreatinineTypeLabel.setText("Normal");

        CreatinineNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreatinineNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        CreatinineNumberLabel.setText("0.9 mg/dl");

        CreatinineLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CreatinineLabel.setForeground(new java.awt.Color(25, 41, 105));
        CreatinineLabel.setText("Creatinine");

        javax.swing.GroupLayout CreatininePanelLayout = new javax.swing.GroupLayout(CreatininePanel);
        CreatininePanel.setLayout(CreatininePanelLayout);
        CreatininePanelLayout.setHorizontalGroup(
            CreatininePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatininePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatininePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreatinineTypeLabel)
                    .addComponent(CreatinineLabel)
                    .addComponent(CreatinineNumberLabel))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        CreatininePanelLayout.setVerticalGroup(
            CreatininePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatininePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatinineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreatinineNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreatinineTypeLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        addAbsolute(CreatininePanel, 720, 230, 110, 80);

        LDLcholesterolPanel.setBackground(new java.awt.Color(238, 243, 249));

        LDLcholesterolTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        LDLcholesterolTypeLabel.setForeground(new java.awt.Color(76, 175, 80));
        LDLcholesterolTypeLabel.setText("Within range");

        LDLcholesterolNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LDLcholesterolNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        LDLcholesterolNumberLabel.setText("102 mg/dl");

        LDLcholesterolLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LDLcholesterolLabel.setForeground(new java.awt.Color(25, 41, 105));
        LDLcholesterolLabel.setText("LDL cholesterol");

        javax.swing.GroupLayout LDLcholesterolPanelLayout = new javax.swing.GroupLayout(LDLcholesterolPanel);
        LDLcholesterolPanel.setLayout(LDLcholesterolPanelLayout);
        LDLcholesterolPanelLayout.setHorizontalGroup(
            LDLcholesterolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LDLcholesterolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LDLcholesterolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDLcholesterolNumberLabel)
                    .addComponent(LDLcholesterolTypeLabel)
                    .addComponent(LDLcholesterolLabel))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        LDLcholesterolPanelLayout.setVerticalGroup(
            LDLcholesterolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LDLcholesterolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LDLcholesterolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LDLcholesterolNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LDLcholesterolTypeLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        addAbsolute(LDLcholesterolPanel, 570, 230, 100, 80);

        HeartratePanel.setBackground(new java.awt.Color(238, 243, 249));

        HeartrateLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        HeartrateLabel.setForeground(new java.awt.Color(25, 41, 105));
        HeartrateLabel.setText("Heart rate");

        HeartrateNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HeartrateNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        HeartrateNumberLabel.setText("76 bpm");

        javax.swing.GroupLayout HeartratePanelLayout = new javax.swing.GroupLayout(HeartratePanel);
        HeartratePanel.setLayout(HeartratePanelLayout);
        HeartratePanelLayout.setHorizontalGroup(
            HeartratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeartratePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HeartratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeartratePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(HeartrateNumberLabel))
                    .addComponent(HeartrateLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        HeartratePanelLayout.setVerticalGroup(
            HeartratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeartratePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeartrateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HeartrateNumberLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAbsolute(HeartratePanel, 660, 400, 90, -1);

        BloodPressurPanel.setBackground(new java.awt.Color(238, 243, 249));

        BloodpressureLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        BloodpressureLabel.setForeground(new java.awt.Color(25, 41, 105));
        BloodpressureLabel.setText("Blood pressure");

        BloodpressureNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BloodpressureNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        BloodpressureNumberLabel.setText("128/82");

        javax.swing.GroupLayout BloodPressurPanelLayout = new javax.swing.GroupLayout(BloodPressurPanel);
        BloodPressurPanel.setLayout(BloodPressurPanelLayout);
        BloodPressurPanelLayout.setHorizontalGroup(
            BloodPressurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BloodPressurPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BloodPressurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BloodPressurPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BloodpressureNumberLabel))
                    .addComponent(BloodpressureLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BloodPressurPanelLayout.setVerticalGroup(
            BloodPressurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BloodPressurPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BloodpressureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BloodpressureNumberLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAbsolute(BloodPressurPanel, 560, 400, -1, -1);

        SpO2Panel.setBackground(new java.awt.Color(238, 243, 249));
        SpO2Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SpO2Label.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        SpO2Label.setForeground(new java.awt.Color(25, 41, 105));
        SpO2Label.setText("SpO2");

        SpO2NumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpO2NumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        SpO2NumberLabel.setText("98%");

        javax.swing.GroupLayout SpO2PanelLayout = new javax.swing.GroupLayout(SpO2Panel);
        SpO2Panel.setLayout(SpO2PanelLayout);
        SpO2PanelLayout.setHorizontalGroup(
            SpO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpO2PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SpO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpO2Label)
                    .addComponent(SpO2NumberLabel))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        SpO2PanelLayout.setVerticalGroup(
            SpO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpO2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpO2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpO2NumberLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAbsolute(SpO2Panel, 560, 480, -1, -1);

        TemperaturePanel.setBackground(new java.awt.Color(238, 243, 249));

        TemperatureLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        TemperatureLabel.setForeground(new java.awt.Color(25, 41, 105));
        TemperatureLabel.setText("Temperature");

        TemperatureNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TemperatureNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        TemperatureNumberLabel.setText("36.8 C");

        javax.swing.GroupLayout TemperaturePanelLayout = new javax.swing.GroupLayout(TemperaturePanel);
        TemperaturePanel.setLayout(TemperaturePanelLayout);
        TemperaturePanelLayout.setHorizontalGroup(
            TemperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturePanelLayout.createSequentialGroup()
                .addGroup(TemperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TemperaturePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TemperatureNumberLabel))
                    .addGroup(TemperaturePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TemperatureLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        TemperaturePanelLayout.setVerticalGroup(
            TemperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TemperatureLabel)
                .addGap(12, 12, 12)
                .addComponent(TemperatureNumberLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAbsolute(TemperaturePanel, 660, 480, 80, -1);

        HbAlcPanel1.setBackground(new java.awt.Color(238, 243, 249));

        HbAlcLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        HbAlcLabel1.setForeground(new java.awt.Color(25, 41, 105));
        HbAlcLabel1.setText("HbAlc");

        HbAlcNumberLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HbAlcNumberLabel1.setForeground(new java.awt.Color(0, 0, 0));
        HbAlcNumberLabel1.setText("72 kg");

        javax.swing.GroupLayout HbAlcPanel1Layout = new javax.swing.GroupLayout(HbAlcPanel1);
        HbAlcPanel1.setLayout(HbAlcPanel1Layout);
        HbAlcPanel1Layout.setHorizontalGroup(
            HbAlcPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HbAlcPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HbAlcPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HbAlcPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(HbAlcNumberLabel1))
                    .addComponent(HbAlcLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        HbAlcPanel1Layout.setVerticalGroup(
            HbAlcPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HbAlcPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HbAlcLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HbAlcNumberLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAbsolute(HbAlcPanel1, 760, 400, 90, -1);

        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane8.setHorizontalScrollBar(null);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane10.setViewportView(jTextArea6);

        jScrollPane8.setViewportView(jScrollPane10);

        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setHorizontalScrollBar(null);

        DiagnosisTextArea.setColumns(20);
        DiagnosisTextArea.setRows(5);
        jScrollPane12.setViewportView(DiagnosisTextArea);

        jScrollPane11.setViewportView(jScrollPane12);

        addAbsolute(jScrollPane11, 30, 280, 210, 50);

        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane13.setHorizontalScrollBar(null);

        MedicationTextArea.setColumns(20);
        MedicationTextArea.setRows(5);
        jScrollPane14.setViewportView(MedicationTextArea);

        jScrollPane13.setViewportView(jScrollPane14);

        addAbsolute(jScrollPane13, 30, 380, 210, 50);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addAbsolute(jSeparator4, 540, 70, 30, 500);

        RespiratoryRatePanel.setBackground(new java.awt.Color(238, 243, 249));

        RespiratoryRateLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        RespiratoryRateLabel.setForeground(new java.awt.Color(25, 41, 105));
        RespiratoryRateLabel.setText("Respiratory Rate ");

        RespiratoryRateNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RespiratoryRateNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        RespiratoryRateNumberLabel.setText("16 breaths/min");

        javax.swing.GroupLayout RespiratoryRatePanelLayout = new javax.swing.GroupLayout(RespiratoryRatePanel);
        RespiratoryRatePanel.setLayout(RespiratoryRatePanelLayout);
        RespiratoryRatePanelLayout.setHorizontalGroup(
            RespiratoryRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespiratoryRatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RespiratoryRateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RespiratoryRatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RespiratoryRateNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RespiratoryRatePanelLayout.setVerticalGroup(
            RespiratoryRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespiratoryRatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RespiratoryRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RespiratoryRateNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        addAbsolute(RespiratoryRatePanel, 753, 480, 100, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Place generated components at their designed coordinates without an extra layout package.
    private void addAbsolute(java.awt.Component component, int x, int y, int width, int height) {
        java.awt.Dimension preferredSize = component.getPreferredSize();
        int actualWidth = width >= 0 ? width : preferredSize.width;
        int actualHeight = height >= 0 ? height : preferredSize.height;

        component.setBounds(x, y, actualWidth, actualHeight);
        getContentPane().add(component);
    }

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Fill the combo box from Derby so the user can choose a patient record.
    private void loadPatientsIntoComboBox() {
        SelectRecordComboBox.removeAllItems();

        try {
            initializeMedicalRecordTables();

            try (Connection con = DatabaseManager.getConnection()) {
                boolean addedAny = addPatientsFromTable(con);

                if (!addedAny) {
                    addPatientsFromInsurance(con);
                }
            }

            if (SelectRecordComboBox.getItemCount() > 0) {
                SelectRecordComboBox.setSelectedIndex(0);
                loadSelectedMedicalRecord();
            } else {
                clearMedicalRecordForm();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Could not load patients from Derby.");
        }
    }

    // Prefer the main PATIENT table so we can show both ID and name.
    private boolean addPatientsFromTable(Connection con) throws SQLException {
        String sql = "SELECT PATIENT_ID, FULL_NAME FROM PATIENT ORDER BY PATIENT_ID";
        boolean addedAny = false;

        try (PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                String patientId = rs.getString("PATIENT_ID");
                String fullName = rs.getString("FULL_NAME");
                SelectRecordComboBox.addItem(fullName == null || fullName.isBlank()
                        ? patientId
                        : patientId + " - " + fullName);
                addedAny = true;
            }
        }

        return addedAny;
    }

    // Fallback to insurance records if PATIENT rows have not been created yet.
    private void addPatientsFromInsurance(Connection con) throws SQLException {
        String sql = "SELECT PATIENT_ID FROM PATIENT_INSURANCE ORDER BY PATIENT_ID";

        try (PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                SelectRecordComboBox.addItem(rs.getString("PATIENT_ID"));
            }
        } catch (SQLException e) {
            if (!"42X05".equals(e.getSQLState())) {
                throw e;
            }
        }
    }

    // Create the backing tables once so this screen can read and save records safely.
    private void initializeMedicalRecordTables() throws SQLException {
        try (Connection con = DatabaseManager.getConnection();
             Statement statement = con.createStatement()) {

            try {
                statement.executeUpdate(
                        "CREATE TABLE PATIENT ("
                        + "PATIENT_ID VARCHAR(50) PRIMARY KEY, "
                        + "FULL_NAME VARCHAR(150) NOT NULL, "
                        + "DATE_OF_BIRTH VARCHAR(30) NOT NULL, "
                        + "GENDER VARCHAR(20), "
                        + "PHONE_NUMBER VARCHAR(30), "
                        + "EMAIL VARCHAR(120), "
                        + "ADDRESS VARCHAR(255), "
                        + "BLOOD_TYPE VARCHAR(10), "
                        + "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")"
                );
            } catch (SQLException e) {
                if (!"X0Y32".equals(e.getSQLState())) {
                    throw e;
                }
            }

            try {
                statement.executeUpdate(
                        "CREATE TABLE MEDICAL_RECORD ("
                        + "PATIENT_ID VARCHAR(50) PRIMARY KEY, "
                        + "DIAGNOSIS VARCHAR(2000), "
                        + "MEDICATION VARCHAR(2000), "
                        + "TREATMENT_PLAN VARCHAR(2000), "
                        + "ALLERGIES VARCHAR(2000), "
                        + "DOCTOR_NOTES VARCHAR(2000), "
                        + "UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")"
                );
            } catch (SQLException e) {
                if (!"X0Y32".equals(e.getSQLState())) {
                    throw e;
                }
            }

            try {
                statement.executeUpdate(
                        "CREATE TABLE LAB_RESULT ("
                        + "PATIENT_ID VARCHAR(50) PRIMARY KEY, "
                        + "HBALC DOUBLE, "
                        + "FASTING_GLUCOSE DOUBLE, "
                        + "LDL_CHOLESTEROL DOUBLE, "
                        + "CREATININE DOUBLE, "
                        + "RESULT_STATUS VARCHAR(30), "
                        + "UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")"
                );
            } catch (SQLException e) {
                if (!"X0Y32".equals(e.getSQLState())) {
                    throw e;
                }
            }

            try {
                statement.executeUpdate(
                        "CREATE TABLE PATIENT_MONITORING ("
                        + "PATIENT_ID VARCHAR(50) PRIMARY KEY, "
                        + "BLOOD_PRESSURE VARCHAR(30), "
                        + "HEART_RATE INT, "
                        + "WEIGHT DOUBLE, "
                        + "SPO2 INT, "
                        + "TEMPERATURE DOUBLE, "
                        + "RESPIRATORY_RATE INT, "
                        + "RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")"
                );
            } catch (SQLException e) {
                if (!"X0Y32".equals(e.getSQLState())) {
                    throw e;
                }
            }
        }
    }

    // Load the selected patient's saved clinical notes into the editable fields.
    private void loadSelectedMedicalRecord() {
        Object selectedItem = SelectRecordComboBox.getSelectedItem();
        if (selectedItem == null) {
            clearMedicalRecordForm();
            return;
        }

        String patientId = extractPatientId(selectedItem.toString());
        String sql = """
                SELECT DIAGNOSIS, MEDICATION, TREATMENT_PLAN, ALLERGIES, DOCTOR_NOTES
                FROM MEDICAL_RECORD
                WHERE PATIENT_ID = ?
                """;

        try {
            initializeMedicalRecordTables();

            try (Connection con = DatabaseManager.getConnection();
                 PreparedStatement pst = con.prepareStatement(sql)) {

                ensureDefaultHealthData(con, patientId);

                pst.setString(1, patientId);

                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        DiagnosisTextArea.setText(defaultText(rs.getString("DIAGNOSIS")));
                        MedicationTextArea.setText(defaultText(rs.getString("MEDICATION")));
                        TreatmentPlanTextArea.setText(defaultText(rs.getString("TREATMENT_PLAN")));
                        AllergiesTextArea.setText(defaultText(rs.getString("ALLERGIES")));
                        DoctorNotesTextArea.setText(defaultText(rs.getString("DOCTOR_NOTES")));
                    } else {
                        clearMedicalRecordForm();
                    }
                }

                loadLaboratoryResults(con, patientId);
                loadPatientMonitoring(con, patientId);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Could not load the selected medical record.");
        }
    }

    // Demo health data lets the lab and monitoring cards work as soon as a patient exists.
    private void ensureDefaultHealthData(Connection con, String patientId) throws SQLException {
        int patientNumber = extractPatientNumber(patientId);

        if (!rowExists(con, "LAB_RESULT", patientId)) {
            String sql = """
                    INSERT INTO LAB_RESULT
                    (PATIENT_ID, HBALC, FASTING_GLUCOSE, LDL_CHOLESTEROL, CREATININE, RESULT_STATUS)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """;

            try (PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setString(1, patientId);
                pst.setDouble(2, 5.8 + (patientNumber % 4) * 0.5);
                pst.setDouble(3, 92 + (patientNumber % 5) * 9);
                pst.setDouble(4, 95 + (patientNumber % 4) * 12);
                pst.setDouble(5, 0.8 + (patientNumber % 3) * 0.2);
                pst.setString(6, "READY");
                pst.executeUpdate();
            }
        }

        if (!rowExists(con, "PATIENT_MONITORING", patientId)) {
            String sql = """
                    INSERT INTO PATIENT_MONITORING
                    (PATIENT_ID, BLOOD_PRESSURE, HEART_RATE, WEIGHT, SPO2, TEMPERATURE, RESPIRATORY_RATE)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """;

            try (PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setString(1, patientId);
                pst.setString(2, (118 + patientNumber % 12) + "/" + (76 + patientNumber % 8));
                pst.setInt(3, 70 + patientNumber % 12);
                pst.setDouble(4, 68 + patientNumber % 18);
                pst.setInt(5, 96 + patientNumber % 4);
                pst.setDouble(6, 36.4 + (patientNumber % 5) * 0.1);
                pst.setInt(7, 14 + patientNumber % 5);
                pst.executeUpdate();
            }
        }
    }

    private boolean rowExists(Connection con, String tableName, String patientId) throws SQLException {
        String sql = "SELECT PATIENT_ID FROM " + tableName + " WHERE PATIENT_ID = ?";

        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, patientId);

            try (ResultSet rs = pst.executeQuery()) {
                return rs.next();
            }
        }
    }

    private void loadLaboratoryResults(Connection con, String patientId) throws SQLException {
        String sql = """
                SELECT HBALC, FASTING_GLUCOSE, LDL_CHOLESTEROL, CREATININE, RESULT_STATUS
                FROM LAB_RESULT
                WHERE PATIENT_ID = ?
                """;

        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, patientId);

            try (ResultSet rs = pst.executeQuery()) {
                if (!rs.next() || !"READY".equalsIgnoreCase(defaultText(rs.getString("RESULT_STATUS")))) {
                    setLaboratoryPending();
                    return;
                }

                double hbAlc = rs.getDouble("HBALC");
                double fastingGlucose = rs.getDouble("FASTING_GLUCOSE");
                double ldlCholesterol = rs.getDouble("LDL_CHOLESTEROL");
                double creatinine = rs.getDouble("CREATININE");

                HbAlcNumberLabel.setText(formatDecimal(hbAlc) + " %");
                setStatus(HbAlcTypeLabel, hbAlc >= 6.5 ? "Elevated" : "Normal", hbAlc >= 6.5);

                FastingGlucoseNumberLabel.setText(formatDecimal(fastingGlucose) + " mg/dl");
                setStatus(FastingGlucoseTypeLabel, fastingGlucose > 100 ? "Above range" : "Normal",
                        fastingGlucose > 100);

                LDLcholesterolNumberLabel.setText(formatDecimal(ldlCholesterol) + " mg/dl");
                setStatus(LDLcholesterolTypeLabel, ldlCholesterol >= 130 ? "High" : "Within range",
                        ldlCholesterol >= 130);

                CreatinineNumberLabel.setText(formatDecimal(creatinine) + " mg/dl");
                setStatus(CreatinineTypeLabel, creatinine > 1.2 ? "High" : "Normal", creatinine > 1.2);
            }
        }
    }

    private void loadPatientMonitoring(Connection con, String patientId) throws SQLException {
        String sql = """
                SELECT BLOOD_PRESSURE, HEART_RATE, WEIGHT, SPO2, TEMPERATURE, RESPIRATORY_RATE
                FROM PATIENT_MONITORING
                WHERE PATIENT_ID = ?
                """;

        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, patientId);

            try (ResultSet rs = pst.executeQuery()) {
                if (!rs.next()) {
                    setMonitoringPending();
                    return;
                }

                BloodpressureNumberLabel.setText(defaultDisplay(rs.getString("BLOOD_PRESSURE")));
                HeartrateNumberLabel.setText(rs.getInt("HEART_RATE") + " bpm");
                HbAlcNumberLabel1.setText(formatDecimal(rs.getDouble("WEIGHT")) + " kg");
                SpO2NumberLabel.setText(rs.getInt("SPO2") + "%");
                TemperatureNumberLabel.setText(formatDecimal(rs.getDouble("TEMPERATURE")) + " C");
                RespiratoryRateNumberLabel.setText(rs.getInt("RESPIRATORY_RATE") + " breaths/min");
            }
        }
    }

    private void setLaboratoryPending() {
        HbAlcNumberLabel.setText("Pending");
        HbAlcTypeLabel.setText("-");
        FastingGlucoseNumberLabel.setText("Pending");
        FastingGlucoseTypeLabel.setText("-");
        LDLcholesterolNumberLabel.setText("Pending");
        LDLcholesterolTypeLabel.setText("-");
        CreatinineNumberLabel.setText("Pending");
        CreatinineTypeLabel.setText("-");
    }

    private void setMonitoringPending() {
        BloodpressureNumberLabel.setText("-");
        HeartrateNumberLabel.setText("-");
        HbAlcNumberLabel1.setText("-");
        SpO2NumberLabel.setText("-");
        TemperatureNumberLabel.setText("-");
        RespiratoryRateNumberLabel.setText("-");
    }

    private void setStatus(javax.swing.JLabel label, String text, boolean warning) {
        label.setText(text);
        label.setForeground(warning ? new java.awt.Color(255, 152, 0) : new java.awt.Color(76, 175, 80));
    }

    private int extractPatientNumber(String patientId) {
        if (patientId != null && patientId.matches("P\\d+")) {
            return Integer.parseInt(patientId.substring(1));
        }

        return 1;
    }

    // Save the current form values for the selected patient, updating first when possible.
    private void saveMedicalRecord() {
        Object selectedItem = SelectRecordComboBox.getSelectedItem();
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "Please register a patient first.");
            return;
        }

        String patientId = extractPatientId(selectedItem.toString());
        String diagnosis = DiagnosisTextArea.getText().trim();
        String medication = MedicationTextArea.getText().trim();
        String treatmentPlan = TreatmentPlanTextArea.getText().trim();
        String allergies = AllergiesTextArea.getText().trim();
        String doctorNotes = DoctorNotesTextArea.getText().trim();

        String updateSql = """
                UPDATE MEDICAL_RECORD
                SET DIAGNOSIS = ?, MEDICATION = ?, TREATMENT_PLAN = ?,
                    ALLERGIES = ?, DOCTOR_NOTES = ?, UPDATED_AT = CURRENT_TIMESTAMP
                WHERE PATIENT_ID = ?
                """;
        String insertSql = """
                INSERT INTO MEDICAL_RECORD
                (PATIENT_ID, DIAGNOSIS, MEDICATION, TREATMENT_PLAN, ALLERGIES, DOCTOR_NOTES)
                VALUES (?, ?, ?, ?, ?, ?)
                """;

        try {
            initializeMedicalRecordTables();

            try (Connection con = DatabaseManager.getConnection();
                 PreparedStatement updatePst = con.prepareStatement(updateSql)) {

                updatePst.setString(1, diagnosis);
                updatePst.setString(2, medication);
                updatePst.setString(3, treatmentPlan);
                updatePst.setString(4, allergies);
                updatePst.setString(5, doctorNotes);
                updatePst.setString(6, patientId);

                int updated = updatePst.executeUpdate();
                if (updated == 0) {
                    try (PreparedStatement insertPst = con.prepareStatement(insertSql)) {
                        insertPst.setString(1, patientId);
                        insertPst.setString(2, diagnosis);
                        insertPst.setString(3, medication);
                        insertPst.setString(4, treatmentPlan);
                        insertPst.setString(5, allergies);
                        insertPst.setString(6, doctorNotes);
                        insertPst.executeUpdate();
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Medical record saved for " + patientId + ".");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Could not save the medical record.");
        }
    }

    // Combo values are shown as "P001 - Name", but the database key is only the ID part.
    private String extractPatientId(String comboValue) {
        int separatorIndex = comboValue.indexOf(" - ");
        return separatorIndex >= 0 ? comboValue.substring(0, separatorIndex) : comboValue;
    }

    private String defaultText(String value) {
        return value == null ? "" : value;
    }

    private String defaultDisplay(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }

    private String formatDecimal(double value) {
        return value == Math.rint(value)
                ? String.valueOf((int) value)
                : String.format(java.util.Locale.US, "%.1f", value);
    }

    private void clearMedicalRecordForm() {
        DiagnosisTextArea.setText("");
        MedicationTextArea.setText("");
        TreatmentPlanTextArea.setText("");
        AllergiesTextArea.setText("");
        DoctorNotesTextArea.setText("");
        setLaboratoryPending();
        setMonitoringPending();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageMedicalRecordUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllergiesLabel;
    private javax.swing.JTextArea AllergiesTextArea;
    private javax.swing.JPanel BloodPressurPanel;
    private javax.swing.JLabel BloodpressureLabel;
    private javax.swing.JLabel BloodpressureNumberLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ClinicalDetailsLabel;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JPanel CommentPanel;
    private javax.swing.JLabel CreatinineLabel;
    private javax.swing.JLabel CreatinineNumberLabel;
    private javax.swing.JPanel CreatininePanel;
    private javax.swing.JLabel CreatinineTypeLabel;
    private javax.swing.JLabel DiagnosisLabel;
    private javax.swing.JTextArea DiagnosisTextArea;
    private javax.swing.JLabel DoctorNotesLabel;
    private javax.swing.JTextArea DoctorNotesTextArea;
    private javax.swing.JLabel FastingGlucoseLabel;
    private javax.swing.JLabel FastingGlucoseNumberLabel;
    private javax.swing.JPanel FastingGlucosePanel;
    private javax.swing.JLabel FastingGlucoseTypeLabel;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JLabel HbAlcLabel;
    private javax.swing.JLabel HbAlcLabel1;
    private javax.swing.JLabel HbAlcNumberLabel;
    private javax.swing.JLabel HbAlcNumberLabel1;
    private javax.swing.JPanel HbAlcPanel;
    private javax.swing.JPanel HbAlcPanel1;
    private javax.swing.JLabel HbAlcTypeLabel;
    private javax.swing.JLabel HeartrateLabel;
    private javax.swing.JLabel HeartrateNumberLabel;
    private javax.swing.JPanel HeartratePanel;
    private javax.swing.JLabel LDLcholesterolLabel;
    private javax.swing.JLabel LDLcholesterolNumberLabel;
    private javax.swing.JPanel LDLcholesterolPanel;
    private javax.swing.JLabel LDLcholesterolTypeLabel;
    private javax.swing.JLabel MedicationLabel;
    private javax.swing.JTextArea MedicationTextArea;
    private javax.swing.JLabel NavLabel;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JLabel PatientMonitoringLabel;
    private javax.swing.JLabel RespiratoryRateLabel;
    private javax.swing.JLabel RespiratoryRateNumberLabel;
    private javax.swing.JPanel RespiratoryRatePanel;
    private javax.swing.JButton SaveChangesButton;
    private javax.swing.JComboBox<String> SelectRecordComboBox;
    private javax.swing.JLabel SelectRecordLabel;
    private javax.swing.JLabel SpO2Label;
    private javax.swing.JLabel SpO2NumberLabel;
    private javax.swing.JPanel SpO2Panel;
    private javax.swing.JLabel TemperatureLabel;
    private javax.swing.JLabel TemperatureNumberLabel;
    private javax.swing.JPanel TemperaturePanel;
    private javax.swing.JLabel TreatmentPlanLabel;
    private javax.swing.JTextArea TreatmentPlanTextArea;
    private javax.swing.JLabel ViewLaboratoryResultsLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}


